# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f092a45338a97b5dbef2499ce95124fdaa4d5178edda7e094204fe9fa697228b1a1a69d26fbc589c8dfd5ba8d0437e6fd34d727860f89730ea1650a45c158d9b

test:
  secret_key_base: e14d0c5e43f70de0f772a2ce2518ba48b84ffd5a06723fa66edcebdd02d4aafa078c3ffe84b0210c967360fb2815df57e39e63e3f5156faaff7617b27ff93980

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
